
name: test build.sh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Build and install
      run: |
        sudo ./build.sh
        sudo apt update
        sudo apt install ./python3-proxmox-helper.deb
    - name: Try to import
      run: |
        python3 -c "from proxmox_helper import ProxmoxHelper"
    - name: Setup tmate session
      if: success() || failure()
      uses: mxschmitt/action-tmate@v3
